'''
Crie um programa que receber um numero e imprime o fatorial daquele numero

1- QUAIS OS DADOS DE ENTRADA NECESSARIOS?
numero
2- O QUE DEVO FAZER COM ESSES DADOS?
calcular o fatorial do numero que for passado para o meu programa exibir na tela
3- QUAIS AS RESTRICOES DESTE PROBLEMA?
numero inteiro positivo
4- QUAL O RESULTADO ESPERADO?
resultado do fatorial desse numero
5 QUAL E A SEQUIENCIA DE PASSOS A SER FEITAS PARA CHEGAR AO RESULTADO ESPERADO?

INPUT: PALAVRA PARA RECEBER DADOS DO USUARIO
PRINT: PALAVRA PARA MOSTRAR O RESULTADO NO CONSOLE
IF CONDICAO: CONDICIONAL QUE CONTROLE SE ALGO DEVE OU NAO SER FEITO
ELSE: CASO O IF NAO SEJA EXECUTADO, EXECUTAR ESSE ELSE
LOOP DE X A Y: LACO DE REPETICAO QUE IRA ITERAR(PASSAR POR CADA ITEM) DE X A Y
LOOP DE X EM Y: LACO DE REPETICAO QUE IRA PASSAR POR CADA ITEM DE X EM UMA COLECAO Y
WHILE X: LACO DE REPETICAO QUE ACONTECERA ENQUANTO UMA CONDICAO FOR VERDADEIRA
'''
input ('Qual e o numero para imprimir o fatorial')
if numero > 0:
    if
